### PR TITLE
Fix nickname slicing when not needed

### LINKED ISSUE #9: AFK removes the first 6 chars of your nickname instead of '[AFK]'
So if you're an idiot, like meself. And you update your nickname, you will wake up to 's Physics Homework'. Making the bot look for the afk string is probably  a better way. Will have a look

### PR DESCRIPTION
**Pull request by MaxTechnics**
This possibly fixes the nicknames being sliced when it's not needed. (#9) Testing still required.

### CODE REVIEW

**Review by TeraBaito — CHANGES_REQUESTED** [review]
You fucked the indenting, use spaces plos

File: src/commands/Utilities/afk.js [hunk 1]
```diff
@@ -29,22 +29,22 @@ module.exports = {
...
+                case 1: // Set
+                    if (length <= 26 && !n) {
+                        message.member.setNickname('[AFK] ' + displayName)
+                            .catch(e => {
+                                if (!(e instanceof DiscordAPIError)) throw e;
+                            });
+                    }
+                    break;
+                case 2: // Remove before
+                    if (length <= 26 && !afk.get(id).flags[1] && displayName.startsWith('[AFK] ')) {
```
Comment (TeraBaito) [inline src/commands/Utilities/afk.js]:
```suggestion
                    if (displayName.startsWith('[AFK] ') && !afk.get(id).flags[1]) {
```

Also here, the `displayName.startsWith('[AFK] ')` implies it was already set, therefore `length <= 26` isn't needed (and actually, this might fuck up because it doesn't take the original displayName.
Please remove the first check (not on the case 1 though)

**Comment by TeraBaito** [comment]
Here's my current `.eslintrc.json`, for if you need that (I should actually be pushing this file)
```json
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es2020": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 11
    },
    "rules": {
        "indent": [
            "error",
            4
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "always"
        ],
        "no-undef": "off",
        "no-unused-vars": "off",
        "no-case-declarations": "off"
    }
}
```

**Comment by TeraBaito** [comment]
I think I can simply commit my suggestion to a new branch, I'll test it there and see how it goes. Thanks for the help though!

**Review by TeraBaito — APPROVED** [review]
Looks good
